version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: logparser_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - logparser

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: logparser_app
    restart: always
    ports:
      - "80:80"
    networks:
      - logparser
    volumes:
      - ./frontend:/app

    depends_on:
      - api

networks:
  logparser:
    driver: bridge
